---

- name: install > Packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-tools
